### ISSUE TITLE
Ue crypto.randomBytes instead of crypto.pseudoRandomBytes

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-register-device#4]
https://github.com/resin-io/resin-register-device/blob/master/lib/crypto.coffee#L21, is there a specific reason why we're using pseudoRandomBytes?
Using crypto.randomBytes would make the uuid a stronger (in case we ever use it for key generation or something like that) and would reduce the probabilities of collisions.

**Comment by jviotti** [comment]
@pcarranzav Since the code was extracted with no modification from the supervisor, I ignore if there was a reason for using `pseudoRandomBytes`. Happy to patch.

Notice that this functionality was moved to the SDK, and other components use the functionality from there instead.

I think we should have a discussion about how to remove the duplication of this logic among various modules.

**Comment by jviotti** [comment]
As discussed privately, we will expose the `generateUUID` functionality and will reuse this module to provide the respective functionality in the SDK.
